# Generated by Django 3.1.2 on 2020-11-01 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
