# Generated by Django 3.1.2 on 2020-11-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_tune_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tune',
            old_name='vexflow_code',
            new_name='vexflow_notes',
        ),
    ]
