# Generated by Django 3.1.2 on 2020-11-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20201101_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
