# Generated by Django 3.1.2 on 2020-11-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20201101_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tune',
            name='id',
        ),
        migrations.AlterField(
            model_name='tune',
            name='date',
            field=models.DateField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
