# Generated by Django 3.1.2 on 2020-11-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20201101_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tune',
            old_name='vexflow_notes',
            new_name='vextab',
        ),
    ]
