# Generated by Django 3.1.2 on 2020-11-02 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0006_auto_20201102_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='successful_guessers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
