# Generated by Django 3.1.3 on 2020-11-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20201103_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='link',
            field=models.URLField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
